### ISSUE TITLE
Error connecting to debugger

### ISSUE THREAD

**Issue by widoyzra** [defold/extension-steam#15]
Description:

When fetching and running this module without making any code changes, I encounter the error: `clojure.lang.ExceptionInfo: Failed to connect to debugger on localhost:8172` The same error occurs when running the example project.

Steps to Reproduce:
1. Fetch the module and run.
2. Attempt to run the example project.

System Information:
- **Defold version:** 1.9.1
- **OS name:** Windows 10
- **OS arch:** amd64
- **GPU:** NVIDIA GeForce RTX 4070Ti
- **GPU Driver:** 4.6.0 NVIDIA 552.44

Logs:
```2024-08-06 19:56:09.449 1061729 [JavaFX Application Thread] INFO  editor.defold-project - {:line 346, :message "Cached compiled build targets in system cache.", :total 312, :retained 158, :unretained 154, :limit 20000}
2024-08-06 19:56:20.733 1073013 [pool-3-thread-2] ERROR editor.error-reporting - {:line 115, :ex-data {:address "localhost", :port 8172}}
clojure.lang.ExceptionInfo: Failed to connect to debugger on localhost:8172
	at editor.debugging.mobdebug$connect_BANG_$fn__61028.invoke(mobdebug.clj:159)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by AGulev** [comment]
What happens if you run using `Ctrl+B` without debugger? Could you please provide **full** console log?

**Comment by widoyzra** [comment]
> What happens if you run using `Ctrl+B` without debugger? Could you please provide **full** console log?

If I run `Ctrl+B`, the project does not start.
this log?
[editor2.2024-08-06.log](https://github.com/user-attachments/files/16513920/editor2.2024-08-06.log)

**Comment by Morgerion** [comment]
> What happens if you run using `Ctrl+B` without debugger? Could you please provide **full** console log?

The console log is not reached - the project is not built to the end, the error occurs somewhere in the Clojure.

**Comment by Morgerion** [comment]
> Steps to Reproduce:
> 
> 1. Fetch the module and run.
> 2. Attempt to run the example project.

I have a similar problem - if i add this steam extension to my steam project, the project just won't start.
No errors.
Selecting "Project->Build" or pressing Ctrl-B will do nothing. Nothing happens.

**Comment by AGulev** [comment]
Did you copy dynamic libraries like it's specified in manual ?

**Comment by Morgerion** [comment]
> Did you copy dynamic libraries like it's specified in manual ?

![image](https://github.com/user-attachments/assets/ff7a086d-bea0-469e-8e8a-6ae77a24b9ce)

But that's advice for macOS, and we have Win10.

**Comment by AGulev** [comment]
Unfortunately, windows doesn't throw the error into console if the error related to the missing dependencies. But the error popups are supressed if it runs the way it runs from the editor. 

The simplest way to see the error would be run exe file of the engine manually :
1. Build the editor
2. Then open `build` folder in your project, your architecture `win32` and run dmengine.exe

If I'm right, you supposed to see a popup with an error, please share it with me.


I assume you'll see missing dynamic library dependency. Defold do not officially support any manipulations with dynamic libraries, but it's planned: https://github.com/defold/defold/issues/3334

You can solve it yourself. 
It's possible by putting DLLs into one of the folders where windows are looking for such libraries, or specify in `PATH` (or registry) where windows should look for dynamic folders in your case.  Read about it here: https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order

**Comment by Morgerion** [comment]
> If I'm right, you supposed to see a popup with an error, please share it with me.
> 
> I assume you'll see missing dynamic library dependency. Defold do not officially support any manipulations with dynamic libraries, but it's planned: [defold/defold#3334](https://github.com/defold/defold/issues/3334)

I had completely forgotten that you need a steam_api.dll to run the Steam SDK. That's really obvious. :(

**Comment by Morgerion** [comment]
![image](https://github.com/user-attachments/assets/ce32bbac-ef64-47c3-8eea-317088f1b377)

**Comment by widoyzra** [comment]
yes, miss steam_api64.dll

thank you

**Comment by AGulev** [comment]
yes, exactly what I thought:
```
Cannot continue code execution because the system did not detect steam_api64.dll. To fix try reinstalling the program.
```
So, yes, [steam_api64.dll](https://github.com/defold/extension-steam/tree/master/steam/lib/x86_64-win32) is something you have to provide for the executable by one of the ways suggested in the article I posted above.

It's unfortunate that such system errors can't be properly shown in the console.
