### ISSUE TITLE
Feature Request - API

### ISSUE THREAD

**Issue by Qwarr** [defold/extension-steam#2]
These are the API calls we currently use for our games:

- [x] steamworks.apps_is_dlc_installed()
- [x] steamworks.user_get_steam_id()
- [x] steamworks.user_stats_set_achievement()
- [x] steamworks.user_stats_clear_achievement()
- [x] steamworks.user_stats_store_stats()
- [x] steamworks.user_stats_reset_all_stats
- [x] steamworks.friends_activate_game_overlay_to_store()

**Comment by britzl** [comment]
Implemented all of the functions
