### ISSUE TITLE
Add "ActivateGameOverlayToWebPage"

### ISSUE THREAD

**Issue by 8bitskull** [defold/extension-steam#5]
Add ActivateGameOverlayToWebPage from: https://partner.steamgames.com/doc/api/ISteamFriends

Use case: We often wish to link to a Steam store page, either to cross-promote or ask for a wishlist in a demo. We already have ActivateGameOverlayToStore which helps with this. However, using ActivateGameOverlayToWebPage for the same purpose lets the player stay in game and view the store page in the overlay (as opposed get switched out of the game and into the Steam app). This is slightly better UX.

**Comment by britzl** [comment]
Added ActivateGameOverlayToWebPage and a bunch of other functions from the SteamFriends part of the API
