### ISSUE TITLE
Unused variable in steam_userstats.cpp generating warning

### ISSUE THREAD

**Issue by 8bitskull** [defold/extension-steam#6]
upload/steam/src/steam_userstats.cpp:31:25: warning: unused variable 's' [-Wunused-variable]
        GlobalStatsReceived_t* s = (GlobalStatsReceived_t*)data;

I get the above warning when bundling. I am also seeing unexplained issues with Linux bundles, but can't be sure it's connected! I haven't tested all possible permutations of game/Defold version, but here's the headlines:
* 1.6.1 Bore Blasters - Linux bundles successfully, but crashes on Steam Deck
* 1.6.2 Void Scrappers - Linux bundles fail, the warning above is quoted

Windows bundles fine for both games.

**Comment by 8bitskull** [comment]
I bundled a 1.6.1 version of Bore Blasters with the only change being that I excluded the extension - this now runs on the Steam Deck!

**Comment by 8bitskull** [comment]
Thought to look for error logs generated on the Steam Deck but none had been created. Engine crashes do tend to get logged in these. Just speculating but maybe it's that this extension fails to initialise on Linux and is therefore closed by Steam, rather than it being a crash.

**Comment by britzl** [comment]
> I get the above warning when bundling.

The warning is not related to the crash.

> 1.6.2 Void Scrappers - Linux bundles fail, the warning above is quoted

Could you please share the full log for the failed build?

> Thought to look for error logs generated on the Steam Deck but none had been created

Does the steam logs include anything from a Defold debug build, for instance prints from your game logic? Or does it seem like the engine crashes before it even runs any code at all?

**Comment by 8bitskull** [comment]
> > 1.6.2 Void Scrappers - Linux bundles fail, the warning above is quoted
> 
> Could you please share the full log for the failed build?

Sure, this should be it! Note that this was from the 1.6.2 beta, run on 18/11.

[log.txt](https://github.com/defold/extension-steam/files/13446945/log.txt)

> > Thought to look for error logs generated on the Steam Deck but none had been created
> 
> Does the steam logs include anything from a Defold debug build, for instance prints from your game logic? Or does it seem like the engine crashes before it even runs any code at all?

I use [Err](https://github.com/subsoap/err) for error logs and this catches both engine crashes and logic errors. No file was generated, hence my guess that no code runs at all.

**Comment by britzl** [comment]
> 1.6.2 Void Scrappers - Linux bundles fail, the warning above is quoted

There's a fix in DefOS. You should update your version.

https://github.com/subsoap/defos/commit/18d95132690d01a9a059613d18a5e9da2a658c7d

> No file was generated, hence my guess that no code runs at all.

Ok, I suppose I need to set up a Linux VM and try to build and run an example project. Or maybe I'll ask in the community first if someone could try to build and run the extension on Linux.

**Comment by 8bitskull** [comment]
> > 1.6.2 Void Scrappers - Linux bundles fail, the warning above is quoted
> 
> There's a fix in DefOS. You should update your version.
> 
> [subsoap/defos@18d9513](https://github.com/subsoap/defos/commit/18d95132690d01a9a059613d18a5e9da2a658c7d)
> 
> > No file was generated, hence my guess that no code runs at all.
> 
> Ok, I suppose I need to set up a Linux VM and try to build and run an example project. Or maybe I'll ask in the community first if someone could try to build and run the extension on Linux.

Thanks for the heads up! Updated DefOS to 2.7.1. Just to make sure, I bundled [Defold 1.6.2 stable](https://github.com/defold/defold/commit/4e156b7cf37a380122aada30dacbf2b590ead76b) and DefOS 2.7.1. Results are the same: Windows bundles fine and Steam extension works, Linux bundles but does not launch on Steam. No error logs generated on Steam Deck. Linux log:

[log.txt](https://github.com/defold/extension-steam/files/13447818/log.txt)

**Comment by 8bitskull** [comment]
Bundling on Defold 1.6.2 with DefOS 2.7.1 seems to work. My two posts above were because my Steam Deck was installing Windows bundles for some reason. Ensuring Linux files are deployed means the builds work as expected. The Steam extension works also.

Closing this issue as I am no longer experiencing the original issues.
