### ISSUE TITLE
App crashes when steam is not open

### ISSUE THREAD

**Issue by Qwarr** [defold/extension-steam#7]
When steam is closed and if you try to call a function the application will hard crash to desktop.

Example: 
```lua
if steam then 
    if steam.apps_is_dlc_installed(dlc_id) then
        --do things 
    end
end
```

Previous extension I think handled steam not running different and never threw an error.

Current work around for me is just setting the extension to false:
```lua
if steam then 
	local status, error = steam.init()
	if status then
		self.steam = true
	else
		self.steam = false 
		steam = false
	end
end
```

**Comment by britzl** [comment]
Thanks. I'm now checking if the systems have initialized properly before calling any Steam API functions. If you call a function when Steam is not initialized the function will simply return nil.
